services:
  - type: web
    name: ecg-monitor
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --timeout 120 --workers 1 --threads 4
    envVars:
      - key: PYTHON_VERSION
        value: "3.10.12"
      - key: TF_CPP_MIN_LOG_LEVEL
        value: "2"
      - key: TF_ENABLE_ONEDNN_OPTS
        value: "0"
